apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-client01-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
  -  ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/antiogenes/rock/volumes/wp/client01
    server: 192.168.99.20
    readOnly: false