apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-client02-deployment
  name: wp-client02-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-client02-deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wp-client02-deployment
    spec:
      containers:
      - image: wordpress:php8.0-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_NAME
          value: db_client02
        - name: WORDPRESS_DB_USER
          value: user_db_client02
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-client02-pass
              key: passwordclient02
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wp-client02-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-client02-persistent-storage
        persistentVolumeClaim:
          claimName: wp-client02-pvc
