apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress-svc-client03
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32003
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-client03-deployment
  type: NodePort