apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32101
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpmyadmin
  type: NodePort