apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
  -  ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/antiogenes/rock/volumes/mysql
    server: 192.168.99.20
    readOnly: false
